### ISSUE TITLE
Problem Statement

### ISSUE THREAD

**Issue by enkiluv** [SE-gmentation/yumyumgood#1]
Problem Statement는 고객의 관점에서 작성하는 것입니다. (원래 고객이 인터뷰하면서 말로 하거나 문서로 제시하는 것입니다.) 그래서 "...이렇게 개발하겠다"는 느낌의 문서가 아니라 "(고객이) 이런저런 문제를 해결하기 위해 이런저런 기능이 있으면 좋겠다"는 느낌의 문서가 되어야 합니다. 이런 점을 감안하여 조금 다듬어보기 바랍니다.

**Comment by yaeoni** [comment]
네, 수정하여 올렸습니다! 피드백 감사합니다 :D

**Comment by enkiluv** [comment]
Well done!
